Il primo approccio alle *exceptions* come metodo per segnalare degli errori è di questo tipo:
```
void loadFile() {
  try {
      open file;
      determine file size;
      allocate memory; 
      read file into memory; 
      close file;
  } catch (fileOpenFailed) { 
      doSomething; 
  } catch(determineSizeFailed) { 
      doSomething; 
  } catch (memoryAllocationFailed) { 
      doSomething; 
  } catch (readFailed) { 
      doSomething; 
  } catch (fileCloseFailed) { 
      doSomething; 
  }
}
```

La classe `Throwable` è la classe padre di tutte le *exception* e provvede per tutte loro un set di metodi in comune:
- `String getMessage()`: restituisce il messaggio dell'errore come stringa;
- `Throwable getCause()`: restituisce la causa dell'errore o `null` nel caso questa non esista o non sia conosciuta;
- `printStackTrace()`: stampa la cronologia dello stack dedicato allo standard error.
Tale classe ha come classi figlie le classi `Exception` ed `Error`:
- `Error` e le sue sottoclassi sono dedicate ad eventi di basso livello nella Macchina Virtuale Java, come `OutOfMemoryError` o `StackOverflowError`;
- `Exception` è dedicato ad eventi interni alle applicazioni (es.`RuntimeException`. Questa classe inoltre e' una sottoclasse speciale, in quanto rappresenta le *unchecked exception*, tra le quali sono incluse anche`ArithmeticException`, `NumberFormatException` e `NullPointerException`).

Le *checked exception* sono quindi tutte le exception escluse quelle presenti nella sottoclasse `RuntimeException`. Se un metodo potrebbe avere una *checked exception*, allora questa va specificata nella scrittura del metodo, altrimenti il programma non compilerebbe. Si fa in questo modo:
```
public static String readLineFromFile() throws FileNotFoundException {
    Scanner scanner = new Scanner(new File("file.txt"));
    return scanner.nextLine();
}
```
Questo tipo di eccezioni vengono usate quando il compilatore richiede l'assoluto controllo di tali errori, contrariamente a quanto si fa per le *unchecked exception*. Per queste infatti, il compilatore compila aldila' del fatto che possa o non possa esserci tale errore, quindi nel caso volessimo una maggior sicurezza, potremmo procedere in questo modo:
```
class Account {

    private long balance = 0;

    public void deposit(long amount) {
        if (amount <= 0) {
            throw new IllegalArgumentException("Incorrect sum " + amount);
        }

        if (amount >= 100_000_000L) {
            throw new IllegalArgumentException("Too large amount");
        }

        balance += amount;
    }

}
```
Anche le *checked exception* possono essere "personalizzate" grazie alla classe `Throwable`:
```
public static String readTextFromFile(String path) throws IOException {
    // find a file by the specified path

    if (!found) {
        throw new IOException("The file " + path + " is not found");
    }

    // read and return text from the file
}
```

Grazie a quanto specificato, il blocco iniziale può essere trasformato in questo modo:
1) Tutti gli errori sono gestiti da un solo blocco di codice:
```
try {
    // code that may throw exceptions
} catch (Exception e) {
    System.out.println("Something goes wrong");
}
```
2) Gli errori di IO sono gestiti da un blocco, il resto da un altro:
```
try {
    // code that throws exceptions
} catch (IOException e) {
    // handling the IOException and its subclasses
} catch (Exception e) {
    // handling the Exception and its subclasses
}
```
3) Tipi di errori diversi possono essere messi insieme e gestiti da un blocco di codice unico:
```
try {
    // code that may throw exceptions
} catch (SQLException | IOException e) {
    // handling SQLException, IOException and their subclasses
    System.out.println(e.getMessage());
} catch (Exception e) {
    // handling any other exceptions
}
```

Al blocco `try-catch` può essere aggiunto il blocco `finally`, il quale ci indica il codice eseguito nel caso in cui nessun errore viene generato nel blocco `try`. 

![](Images/Pasted%20image%2020240718113156.png)